### ISSUE TITLE
netcdf4 backend required

### ISSUE THREAD

**Issue by lukasbaumbach** [cwerner/lpjguesstools#4]
With the stated requirements, lgt_creatinput throws an error: `ValueError: invalid format for scipy.io.netcdf backend: 'NETCDF4_CLASSIC`. This is due to the fact, that scipy is used as netcdf backend and only supports netcdf3 formats. For writing to the netcdf4_classic format, netcdf4 needs to be installed/added to package requirements.

**Comment by cwerner** [comment]
This is an easy one. Thus, I simply added netcdf4 to the requirements.txt file in master. See commit bd1c66e.
